apiVersion: v1
kind: Service
metadata:
  name: gpt-hf-service
  labels:
    app: gpt-huggingface
spec:
  type: NodePort
  selector:
    app: gpt-hf-pod
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30007
    protocol: TCP
    name: http